apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: mogenius-argo-cd
  labels:
    managed-by: mogenius
spec:
  destination:
    name: in-cluster
    namespace: podinfo
  syncPolicy:
    automated:
      prune: true
      enabled: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: mogenius
  source:
    repoURL: https://helm.mogenius.com/public
    targetRevision: 1.2.2
    chart: moac
    helm:
      releaseName: podinfo
      valuesObject:
        services:
          - podinfo:
              labels:
                app.kubernetes.io/name: podinfo
                app.kubernetes.io/version: 6.9.2
              clusterIP: 10.43.255.94
              clusterIPs:
                - 10.43.255.94
              internalTrafficPolicy: Cluster
              ipFamilies:
                - IPv4
              ipFamilyPolicy: SingleStack
              ports:
                - name: http
                  port: 9898
                  protocol: TCP
                  targetPort: http
                - name: grpc
                  port: 9999
                  protocol: TCP
                  targetPort: grpc
              selector:
                app.kubernetes.io/name: podinfo
              sessionAffinity: None
              type: ClusterIP
        rawResources:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              annotations: {}
              labels:
                app.kubernetes.io/name: podinfo
                app.kubernetes.io/version: 6.9.2
              name: podinfo
              namespace: podinfo
            spec:
              progressDeadlineSeconds: 600
              replicas: 1
              revisionHistoryLimit: 10
              selector:
                matchLabels:
                  app.kubernetes.io/name: podinfo
              strategy:
                rollingUpdate:
                  maxSurge: 25%
                  maxUnavailable: 1
                type: RollingUpdate
              template:
                metadata:
                  annotations:
                    prometheus.io/port: '9898'
                    prometheus.io/scrape: 'true'
                  labels:
                    app.kubernetes.io/name: podinfo
                spec:
                  containers:
                    - command:
                        - ./podinfo
                        - '--port=9898'
                        - '--cert-path=/data/cert'
                        - '--port-metrics=9797'
                        - '--grpc-port=9999'
                        - '--grpc-service-name=podinfo'
                        - '--level=info'
                        - '--random-delay=false'
                        - '--random-error=false'
                      env:
                        - name: PODINFO_UI_COLOR
                          value: '#34577c'
                      image: ghcr.io/stefanprodan/podinfo:6.9.2
                      imagePullPolicy: IfNotPresent
                      livenessProbe:
                        exec:
                          command:
                            - podcli
                            - check
                            - http
                            - localhost:9898/healthz
                        failureThreshold: 3
                        initialDelaySeconds: 1
                        periodSeconds: 10
                        successThreshold: 1
                        timeoutSeconds: 5
                      name: podinfo
                      ports:
                        - containerPort: 9898
                          name: http
                          protocol: TCP
                        - containerPort: 9797
                          name: http-metrics
                          protocol: TCP
                        - containerPort: 9999
                          name: grpc
                          protocol: TCP
                      readinessProbe:
                        exec:
                          command:
                            - podcli
                            - check
                            - http
                            - localhost:9898/readyz
                        failureThreshold: 3
                        initialDelaySeconds: 1
                        periodSeconds: 10
                        successThreshold: 1
                        timeoutSeconds: 5
                      resources:
                        requests:
                          cpu: 1m
                          memory: 16Mi
                      terminationMessagePath: /dev/termination-log
                      terminationMessagePolicy: File
                      volumeMounts:
                        - mountPath: /data
                          name: data
                  dnsPolicy: ClusterFirst
                  restartPolicy: Always
                  schedulerName: default-scheduler
                  securityContext: {}
                  terminationGracePeriodSeconds: 30
                  volumes:
                    - emptyDir: {}
                      name: data
